language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
provider: heroku
  api_key:
    secure: dd26119c-27a8-4422-9e38-6375da52dbb3
  app: